language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules

before_install:
  - npm set progress=false

install:
  - npm install

script:
  - npm test
  - npm run test:coverage

after_success:
  - npm run coverage
